// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: aiorder.proto

package aiorder

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单状态枚举
type AIOrderStatus int32

const (
	AIOrderStatus_UNKNOWN    AIOrderStatus = 0
	AIOrderStatus_PENDING    AIOrderStatus = 1 // 待处理
	AIOrderStatus_PROCESSING AIOrderStatus = 2 // 处理中
	AIOrderStatus_COMPLETED  AIOrderStatus = 3 // 已完成
	AIOrderStatus_FAILED     AIOrderStatus = 4 // 失败
	AIOrderStatus_CANCELLED  AIOrderStatus = 5 // 已取消
)

// Enum value maps for AIOrderStatus.
var (
	AIOrderStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "PROCESSING",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLED",
	}
	AIOrderStatus_value = map[string]int32{
		"UNKNOWN":    0,
		"PENDING":    1,
		"PROCESSING": 2,
		"COMPLETED":  3,
		"FAILED":     4,
		"CANCELLED":  5,
	}
)

func (x AIOrderStatus) Enum() *AIOrderStatus {
	p := new(AIOrderStatus)
	*p = x
	return p
}

func (x AIOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AIOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aiorder_proto_enumTypes[0].Descriptor()
}

func (AIOrderStatus) Type() protoreflect.EnumType {
	return &file_aiorder_proto_enumTypes[0]
}

func (x AIOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AIOrderStatus.Descriptor instead.
func (AIOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{0}
}

// AI订单信息
type AIOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId      uint64        `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId       uint32        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelName    string        `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`           // AI模型名称
	Prompt       string        `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`                                  // 提示词
	Status       AIOrderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=aiorder.AIOrderStatus" json:"status,omitempty"`      // 订单状态
	Result       string        `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`                                  // 生成结果
	CreateTime   int64         `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`       // 创建时间
	CompleteTime int64         `protobuf:"varint,8,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"` // 完成时间
}

func (x *AIOrder) Reset() {
	*x = AIOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiorder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIOrder) ProtoMessage() {}

func (x *AIOrder) ProtoReflect() protoreflect.Message {
	mi := &file_aiorder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIOrder.ProtoReflect.Descriptor instead.
func (*AIOrder) Descriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{0}
}

func (x *AIOrder) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AIOrder) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AIOrder) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AIOrder) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AIOrder) GetStatus() AIOrderStatus {
	if x != nil {
		return x.Status
	}
	return AIOrderStatus_UNKNOWN
}

func (x *AIOrder) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AIOrder) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AIOrder) GetCompleteTime() int64 {
	if x != nil {
		return x.CompleteTime
	}
	return 0
}

type CreateAIOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelName string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Prompt    string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *CreateAIOrderReq) Reset() {
	*x = CreateAIOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiorder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAIOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIOrderReq) ProtoMessage() {}

func (x *CreateAIOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_aiorder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIOrderReq.ProtoReflect.Descriptor instead.
func (*CreateAIOrderReq) Descriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAIOrderReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAIOrderReq) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CreateAIOrderReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type CreateAIOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId uint64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *CreateAIOrderResp) Reset() {
	*x = CreateAIOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiorder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAIOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIOrderResp) ProtoMessage() {}

func (x *CreateAIOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_aiorder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIOrderResp.ProtoReflect.Descriptor instead.
func (*CreateAIOrderResp) Descriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAIOrderResp) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetAIOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId uint64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId  uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAIOrderReq) Reset() {
	*x = GetAIOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiorder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAIOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIOrderReq) ProtoMessage() {}

func (x *GetAIOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_aiorder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIOrderReq.ProtoReflect.Descriptor instead.
func (*GetAIOrderReq) Descriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{3}
}

func (x *GetAIOrderReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetAIOrderReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAIOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *AIOrder `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *GetAIOrderResp) Reset() {
	*x = GetAIOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiorder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAIOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIOrderResp) ProtoMessage() {}

func (x *GetAIOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_aiorder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIOrderResp.ProtoReflect.Descriptor instead.
func (*GetAIOrderResp) Descriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{4}
}

func (x *GetAIOrderResp) GetOrder() *AIOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelAIOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId uint64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId  uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CancelAIOrderReq) Reset() {
	*x = CancelAIOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiorder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelAIOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAIOrderReq) ProtoMessage() {}

func (x *CancelAIOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_aiorder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAIOrderReq.ProtoReflect.Descriptor instead.
func (*CancelAIOrderReq) Descriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{5}
}

func (x *CancelAIOrderReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelAIOrderReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelAIOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CancelAIOrderResp) Reset() {
	*x = CancelAIOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiorder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelAIOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAIOrderResp) ProtoMessage() {}

func (x *CancelAIOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_aiorder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAIOrderResp.ProtoReflect.Descriptor instead.
func (*CancelAIOrderResp) Descriptor() ([]byte, []int) {
	return file_aiorder_proto_rawDescGZIP(), []int{6}
}

func (x *CancelAIOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_aiorder_proto protoreflect.FileDescriptor

var file_aiorder_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x82, 0x02, 0x0a, 0x07, 0x41, 0x49, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12,
	0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x62, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x22, 0x2e, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x49, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x43, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x22, 0x46, 0x0a, 0x10, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0x63, 0x0a, 0x0d, 0x41, 0x49, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x32, 0xe5, 0x01, 0x0a,
	0x0e, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x48, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x19, 0x2e, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x61, 0x69,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x49, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x61, 0x69,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x49, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x49, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x77, 0x68, 0x6c, 0x78, 0x62, 0x64, 0x2f, 0x67, 0x6f, 0x6d, 0x61, 0x6c, 0x6c,
	0x2f, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x61, 0x69, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_aiorder_proto_rawDescOnce sync.Once
	file_aiorder_proto_rawDescData = file_aiorder_proto_rawDesc
)

func file_aiorder_proto_rawDescGZIP() []byte {
	file_aiorder_proto_rawDescOnce.Do(func() {
		file_aiorder_proto_rawDescData = protoimpl.X.CompressGZIP(file_aiorder_proto_rawDescData)
	})
	return file_aiorder_proto_rawDescData
}

var file_aiorder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aiorder_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_aiorder_proto_goTypes = []interface{}{
	(AIOrderStatus)(0),        // 0: aiorder.AIOrderStatus
	(*AIOrder)(nil),           // 1: aiorder.AIOrder
	(*CreateAIOrderReq)(nil),  // 2: aiorder.CreateAIOrderReq
	(*CreateAIOrderResp)(nil), // 3: aiorder.CreateAIOrderResp
	(*GetAIOrderReq)(nil),     // 4: aiorder.GetAIOrderReq
	(*GetAIOrderResp)(nil),    // 5: aiorder.GetAIOrderResp
	(*CancelAIOrderReq)(nil),  // 6: aiorder.CancelAIOrderReq
	(*CancelAIOrderResp)(nil), // 7: aiorder.CancelAIOrderResp
}
var file_aiorder_proto_depIdxs = []int32{
	0, // 0: aiorder.AIOrder.status:type_name -> aiorder.AIOrderStatus
	1, // 1: aiorder.GetAIOrderResp.order:type_name -> aiorder.AIOrder
	2, // 2: aiorder.AIOrderService.CreateAIOrder:input_type -> aiorder.CreateAIOrderReq
	4, // 3: aiorder.AIOrderService.GetAIOrder:input_type -> aiorder.GetAIOrderReq
	6, // 4: aiorder.AIOrderService.CancelAIOrder:input_type -> aiorder.CancelAIOrderReq
	3, // 5: aiorder.AIOrderService.CreateAIOrder:output_type -> aiorder.CreateAIOrderResp
	5, // 6: aiorder.AIOrderService.GetAIOrder:output_type -> aiorder.GetAIOrderResp
	7, // 7: aiorder.AIOrderService.CancelAIOrder:output_type -> aiorder.CancelAIOrderResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aiorder_proto_init() }
func file_aiorder_proto_init() {
	if File_aiorder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aiorder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiorder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAIOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiorder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAIOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiorder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAIOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiorder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAIOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiorder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelAIOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiorder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelAIOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aiorder_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aiorder_proto_goTypes,
		DependencyIndexes: file_aiorder_proto_depIdxs,
		EnumInfos:         file_aiorder_proto_enumTypes,
		MessageInfos:      file_aiorder_proto_msgTypes,
	}.Build()
	File_aiorder_proto = out.File
	file_aiorder_proto_rawDesc = nil
	file_aiorder_proto_goTypes = nil
	file_aiorder_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.1. DO NOT EDIT.

type AIOrderService interface {
	CreateAIOrder(ctx context.Context, req *CreateAIOrderReq) (res *CreateAIOrderResp, err error)
	GetAIOrder(ctx context.Context, req *GetAIOrderReq) (res *GetAIOrderResp, err error)
	CancelAIOrder(ctx context.Context, req *CancelAIOrderReq) (res *CancelAIOrderResp, err error)
}
