// Code generated by Kitex v0.9.1. DO NOT EDIT.

package ruleservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	auth "github.com/whlxbd/gomall/rpc_gen/kitex_gen/auth"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Create(ctx context.Context, Req *auth.CreateReq, callOptions ...callopt.Option) (r *auth.CreateResp, err error)
	List(ctx context.Context, Req *auth.ListReq, callOptions ...callopt.Option) (r *auth.ListResp, err error)
	Delete(ctx context.Context, Req *auth.DeleteReq, callOptions ...callopt.Option) (r *auth.DeleteResp, err error)
	Get(ctx context.Context, Req *auth.GetReq, callOptions ...callopt.Option) (r *auth.GetResp, err error)
	Update(ctx context.Context, Req *auth.UpdateReq, callOptions ...callopt.Option) (r *auth.UpdateResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRuleServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRuleServiceClient struct {
	*kClient
}

func (p *kRuleServiceClient) Create(ctx context.Context, Req *auth.CreateReq, callOptions ...callopt.Option) (r *auth.CreateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Create(ctx, Req)
}

func (p *kRuleServiceClient) List(ctx context.Context, Req *auth.ListReq, callOptions ...callopt.Option) (r *auth.ListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, Req)
}

func (p *kRuleServiceClient) Delete(ctx context.Context, Req *auth.DeleteReq, callOptions ...callopt.Option) (r *auth.DeleteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, Req)
}

func (p *kRuleServiceClient) Get(ctx context.Context, Req *auth.GetReq, callOptions ...callopt.Option) (r *auth.GetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Get(ctx, Req)
}

func (p *kRuleServiceClient) Update(ctx context.Context, Req *auth.UpdateReq, callOptions ...callopt.Option) (r *auth.UpdateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Update(ctx, Req)
}
