// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aiorderservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	aiorder "github.com/whlxbd/gomall/rpc_gen/kitex_gen/aiorder"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"QueryOrder": kitex.NewMethodInfo(
		queryOrderHandler,
		newQueryOrderArgs,
		newQueryOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SimulateOrder": kitex.NewMethodInfo(
		simulateOrderHandler,
		newSimulateOrderArgs,
		newSimulateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	aIOrderServiceServiceInfo                = NewServiceInfo()
	aIOrderServiceServiceInfoForClient       = NewServiceInfoForClient()
	aIOrderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIOrderServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aIOrderServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aIOrderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AIOrderService"
	handlerType := (*aiorder.AIOrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "aiorder",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func queryOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(aiorder.QueryOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(aiorder.AIOrderService).QueryOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QueryOrderArgs:
		success, err := handler.(aiorder.AIOrderService).QueryOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQueryOrderArgs() interface{} {
	return &QueryOrderArgs{}
}

func newQueryOrderResult() interface{} {
	return &QueryOrderResult{}
}

type QueryOrderArgs struct {
	Req *aiorder.QueryOrderReq
}

func (p *QueryOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(aiorder.QueryOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *QueryOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *QueryOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *QueryOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QueryOrderArgs) Unmarshal(in []byte) error {
	msg := new(aiorder.QueryOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryOrderArgs_Req_DEFAULT *aiorder.QueryOrderReq

func (p *QueryOrderArgs) GetReq() *aiorder.QueryOrderReq {
	if !p.IsSetReq() {
		return QueryOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QueryOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QueryOrderResult struct {
	Success *aiorder.QueryOrderResp
}

var QueryOrderResult_Success_DEFAULT *aiorder.QueryOrderResp

func (p *QueryOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(aiorder.QueryOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *QueryOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *QueryOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *QueryOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QueryOrderResult) Unmarshal(in []byte) error {
	msg := new(aiorder.QueryOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryOrderResult) GetSuccess() *aiorder.QueryOrderResp {
	if !p.IsSetSuccess() {
		return QueryOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*aiorder.QueryOrderResp)
}

func (p *QueryOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QueryOrderResult) GetResult() interface{} {
	return p.Success
}

func simulateOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(aiorder.SimulateOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(aiorder.AIOrderService).SimulateOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SimulateOrderArgs:
		success, err := handler.(aiorder.AIOrderService).SimulateOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SimulateOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSimulateOrderArgs() interface{} {
	return &SimulateOrderArgs{}
}

func newSimulateOrderResult() interface{} {
	return &SimulateOrderResult{}
}

type SimulateOrderArgs struct {
	Req *aiorder.SimulateOrderReq
}

func (p *SimulateOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(aiorder.SimulateOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SimulateOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SimulateOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SimulateOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SimulateOrderArgs) Unmarshal(in []byte) error {
	msg := new(aiorder.SimulateOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SimulateOrderArgs_Req_DEFAULT *aiorder.SimulateOrderReq

func (p *SimulateOrderArgs) GetReq() *aiorder.SimulateOrderReq {
	if !p.IsSetReq() {
		return SimulateOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SimulateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SimulateOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SimulateOrderResult struct {
	Success *aiorder.SimulateOrderResp
}

var SimulateOrderResult_Success_DEFAULT *aiorder.SimulateOrderResp

func (p *SimulateOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(aiorder.SimulateOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SimulateOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SimulateOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SimulateOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SimulateOrderResult) Unmarshal(in []byte) error {
	msg := new(aiorder.SimulateOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SimulateOrderResult) GetSuccess() *aiorder.SimulateOrderResp {
	if !p.IsSetSuccess() {
		return SimulateOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SimulateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*aiorder.SimulateOrderResp)
}

func (p *SimulateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SimulateOrderResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) QueryOrder(ctx context.Context, Req *aiorder.QueryOrderReq) (r *aiorder.QueryOrderResp, err error) {
	var _args QueryOrderArgs
	_args.Req = Req
	var _result QueryOrderResult
	if err = p.c.Call(ctx, "QueryOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SimulateOrder(ctx context.Context, Req *aiorder.SimulateOrderReq) (r *aiorder.SimulateOrderResp, err error) {
	var _args SimulateOrderArgs
	_args.Req = Req
	var _result SimulateOrderResult
	if err = p.c.Call(ctx, "SimulateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
