// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aiorderservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	aiorder "github.com/whlxbd/gomall/rpc_gen/kitex_gen/aiorder"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAIOrder(ctx context.Context, Req *aiorder.CreateAIOrderReq, callOptions ...callopt.Option) (r *aiorder.CreateAIOrderResp, err error)
	GetAIOrder(ctx context.Context, Req *aiorder.GetAIOrderReq, callOptions ...callopt.Option) (r *aiorder.GetAIOrderResp, err error)
	CancelAIOrder(ctx context.Context, Req *aiorder.CancelAIOrderReq, callOptions ...callopt.Option) (r *aiorder.CancelAIOrderResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIOrderServiceClient struct {
	*kClient
}

func (p *kAIOrderServiceClient) CreateAIOrder(ctx context.Context, Req *aiorder.CreateAIOrderReq, callOptions ...callopt.Option) (r *aiorder.CreateAIOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAIOrder(ctx, Req)
}

func (p *kAIOrderServiceClient) GetAIOrder(ctx context.Context, Req *aiorder.GetAIOrderReq, callOptions ...callopt.Option) (r *aiorder.GetAIOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAIOrder(ctx, Req)
}

func (p *kAIOrderServiceClient) CancelAIOrder(ctx context.Context, Req *aiorder.CancelAIOrderReq, callOptions ...callopt.Option) (r *aiorder.CancelAIOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelAIOrder(ctx, Req)
}
